# src/agent/state.py
"""Agent state definitions for SocrAItes.

This module defines the structured state that is passed between LangGraph nodes.
It uses ``TypedDict`` for static type checking while remaining JSON-serializable.
"""

from __future__ import annotations

from typing import TypedDict, List, Dict, Any

class AgentState(TypedDict, total=False):
    """TypedDict representing the mutable state of a conversation turn.

    Core Agent fields:
    - ``messages``: List of message dicts exchanged so far.
    - ``socratic_depth``: Current depth mode (0=Light, 1=Standard, 2=Deep).
    - ``frustration_level``: Counter of detected frustration signals.
    - ``next_step``: Signal for routing (e.g., 'planner', 'direct_response').
    - ``plan``: The execution plan generated by the Planner.
    - ``sub_agents``: Which sub-agents to invoke this turn (retrieval/dialogue/diagnosis).
    - ``draft_answer``: The final response synthesized by the Supervisor.
    - ``evaluation``: Results from the Evaluator node.
    - ``retry_count``: How many times the Evaluator has triggered a retry.
    - ``session_id``: UUID for the current database session.

    Sub Agent output fields:
    - ``retrieved_docs``: Document chunks from Retrieval Agent.
    - ``socratic_response``: Socratic question/hint from Socratic Dialogue Agent.
    - ``diagnosis_result``: Tool results + analysis from Diagnosis Agent.

    Misc:
    - ``contextualized_query``: Reformulated query from Coordinator.
    - ``tool_results``: Flattened tool results for API response.
    - ``pending_quiz``: Quiz items awaiting user answers.
    """

    messages: List[Dict[str, Any]]
    socratic_depth: int
    frustration_level: int
    next_step: str
    plan: str
    sub_agents: List[str]
    draft_answer: str
    evaluation: Dict[str, Any]
    retry_count: int
    session_id: str
    contextualized_query: str
    # Sub Agent outputs
    retrieved_docs: List[Any]
    socratic_response: str
    diagnosis_result: Dict[str, Any]
    # Misc
    tool_results: List[Dict[str, Any]]
    pending_quiz: List[Dict[str, Any]]

# Default initial state
DEFAULT_STATE: AgentState = {
    "messages": [],
    "socratic_depth": 1,
    "frustration_level": 0,
    "next_step": "",
    "plan": "",
    "sub_agents": [],
    "draft_answer": "",
    "evaluation": {},
    "retry_count": 0,
    "session_id": "",
    "contextualized_query": "",
    "retrieved_docs": [],
    "socratic_response": "",
    "diagnosis_result": {},
    "tool_results": [],
    "pending_quiz": [],
}
